/**
 * 能力标签种子数据
 * 定义路由能力标签及其要求，用于智能路由决策
 * 最后更新：2026-02-10
 */

export interface CapabilityTagData {
  tagId: string;
  name: string;
  description?: string;
  category: string;
  priority: number;
  requiredProtocol?: string;
  requiredSkills?: string[];
  requiredModels?: string[];
  requiresExtendedThinking?: boolean;
  requiresCacheControl?: boolean;
  requiresVision?: boolean;
  requiresFunctionCalling?: boolean;
  maxCostPerMToken?: number;
  minContextWindow?: number;
  maxLatencyMs?: number;
  isBuiltin: boolean;
}

export const CAPABILITY_TAGS_DATA: CapabilityTagData[] = [
  {
    tagId: 'deep-reasoning',
    name: '深度推理',
    description: '需要复杂推理、分析的任务，使用 Extended Thinking 或推理模型',
    category: 'reasoning',
    priority: 100,
    requiredModels: [
      'claude-opus-4-6',
      'claude-opus-4-5-20251101',
      'claude-sonnet-4-5-20250929',
      'claude-sonnet-4-5-20250929-thinking',
      'o3',
      'gpt-5-pro',
      'gpt-5.2-pro',
      'grok-4',
      'grok-3-reasoner-r',
      'deepseek-r1',
      'deepseek-reasoner',
      'doubao-seed-1.6-thinking',
      'doubao-seed-1-6-thinking-250715',
      'doubao-1.5-thinking-pro',
      'qwen-3.0-thinking',
      'qwq-plus',
      'kimi-k2',
    ],
    requiresExtendedThinking: true,
    isBuiltin: true,
  },
  {
    tagId: 'fast-reasoning',
    name: '快速推理',
    description: '需要快速响应的推理任务',
    category: 'reasoning',
    priority: 50,
    requiredProtocol: 'openai-compatible',
    requiredModels: [
      'gpt-4o',
      'gpt-4.1',
      'gpt-5-mini',
      'gpt-5-nano',
      'o4-mini',
      'claude-sonnet-4-20250514',
      'claude-haiku-4-5-20251001',
      'deepseek-v3',
      'deepseek-v3-2-251201',
      'deepseek-chat',
      'gemini-2.5-flash',
      'gemini-3-flash-preview',
      'grok-3-mini',
      'doubao-seed-1-6-flash',
      'doubao-1.5-lite',
      'qwen-turbo',
      'glm-4.5-air',
      'moonshot-v1-auto',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'web-search',
    name: '网络搜索',
    description: '需要实时搜索互联网信息',
    category: 'search',
    priority: 80,
    requiredSkills: ['web_search'],
    requiredModels: [
      'deepseek-v3-search',
      'deepseek-reasoner-search',
      'qwen-max-search',
      'doubao-1.5-pro-32k-search',
      'doubao-1-5-thinking-pro-search',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'code-execution',
    name: '代码执行',
    description: '需要执行代码并返回结果',
    category: 'code',
    priority: 70,
    requiredSkills: ['code_runner'],
    isBuiltin: true,
  },
  {
    tagId: 'cost-optimized',
    name: '成本优化',
    description: '优先使用高性价比模型',
    category: 'cost',
    priority: 90,
    requiredModels: [
      'deepseek-v3',
      'deepseek-v3-2-251201',
      'deepseek-chat',
      'gpt-4o-mini',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'gpt-5-mini',
      'gpt-5-nano',
      'gemini-2.5-flash',
      'gemini-3-flash-preview',
      'doubao-1.5-pro-32k',
      'doubao-1.5-lite',
      'doubao-seed-1-6-flash',
      'claude-haiku-4-5-20251001',
      'qwen-turbo',
      'glm-4.5-air',
      'moonshot-v1-8k',
    ],
    maxCostPerMToken: 1,
    isBuiltin: true,
  },
  {
    tagId: 'long-context',
    name: '长上下文',
    description: '需要处理超长文档或对话历史（100K+ tokens）',
    category: 'context',
    priority: 60,
    requiredModels: [
      'gemini-2.5-pro',
      'gemini-3-pro-preview',
      'gpt-5',
      'gpt-5.1',
      'gpt-5.2',
      'grok-4',
      'claude-opus-4-6',
      'claude-opus-4-5-20251101',
      'claude-sonnet-4-5-20250929',
      'doubao-1.5-pro-256k',
      'qwen-long',
      'moonshot-v1-128k',
      'kimi-k2',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'vision',
    name: '视觉理解',
    description: '需要处理图像、视频等多模态内容',
    category: 'vision',
    priority: 75,
    requiredModels: [
      'gpt-4o',
      'gpt-4.1',
      'gpt-5',
      'gpt-5.2',
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-5-20251101',
      'claude-opus-4-6',
      'gemini-2.5-pro',
      'gemini-3-pro-preview',
      'grok-4',
      'doubao-1.5-vision-pro-32k',
      'doubao-seed-1-6-vision',
      'doubao-1.5-thinking-vision-pro',
      'qwen-vl-max',
      'qwen-vl-max-latest',
      'qvq-max',
      'glm-4.5',
    ],
    requiresVision: true,
    isBuiltin: true,
  },
  {
    tagId: 'coding',
    name: '编程任务',
    description: '代码生成、调试、重构等编程相关任务',
    category: 'code',
    priority: 65,
    requiredModels: [
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-5-20251101',
      'claude-opus-4-6',
      'gpt-5-codex',
      'gpt-5.1-codex',
      'gpt-5.2-codex',
      'deepseek-v3',
      'deepseek-v3-2-251201',
      'grok-code-fast-1',
      'o3',
      'o4-mini',
      'qwen-3.0',
      'qwen3-max',
      'kimi-k2',
      'glm-4.5',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'image-generation',
    name: '图像生成',
    description: '文本到图像生成任务',
    category: 'creative',
    priority: 70,
    requiredModels: [
      'Midjourney',
      'gpt-image-1',
      'gpt-image-1.5',
      'gpt-image-1.5-plus',
      'flux-kontext-pro',
      'flux-kontext-max',
      'ideogram-generate-v3',
      'doubao-seedream-4-5-251128',
      'doubao-seedream-3.0-t2i',
      'qwen-image-plus',
      'grok-4-image',
      'kling-image-o1',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'video-generation',
    name: '视频生成',
    description: '文本/图像到视频生成任务',
    category: 'creative',
    priority: 72,
    requiredModels: [
      'sora-2',
      'sora-2-pro',
      'veo3',
      'veo3.1',
      'veo3.1-pro',
      'kling-v2.6-pro',
      'kling-video-o1-pro',
      'hailuo-2.3-pro',
      'viduq3-pro',
      'wan-2.6',
      'wan2.1-14b',
      'doubao-seedance-1-5-pro-251215',
      'doubao-seedance-1-0-pro',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'audio-tts',
    name: '语音合成',
    description: '文本到语音合成任务',
    category: 'audio',
    priority: 55,
    requiredModels: [
      'gpt-4o-mini-tts',
      'speech-2.6-hd',
      'speech-2.5-hd-preview',
      'gemini-2.5-flash-preview-tts',
      'gemini-2.5-pro-preview-tts',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'creative',
    name: '创意写作',
    description: '需要高创造力的写作、故事、营销文案等任务',
    category: 'creative',
    priority: 58,
    requiredModels: [
      'claude-opus-4-6',
      'claude-opus-4-5-20251101',
      'gpt-5-pro',
      'gpt-5.2-pro',
      'grok-4',
      'gemini-3-pro-preview',
      'doubao-1.5-character-pro-32k',
    ],
    isBuiltin: true,
  },
  {
    tagId: '3d-generation',
    name: '3D 生成',
    description: '3D 模型生成任务',
    category: 'creative',
    priority: 45,
    requiredModels: ['tripo3d-v2.5'],
    isBuiltin: true,
  },
  {
    tagId: 'embedding',
    name: '向量嵌入',
    description: '文本向量化任务',
    category: 'embedding',
    priority: 40,
    requiredModels: [
      'doubao-embedding',
      'doubao-embedding-large',
      'doubao-embedding-vision',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'chinese-optimized',
    name: '中文优化',
    description: '中文任务优化，优先使用中文能力强的模型',
    category: 'language',
    priority: 55,
    requiredModels: [
      'doubao-seed-1-6',
      'doubao-seed-1-6-251015',
      'doubao-1.5-pro-32k',
      'doubao-1.5-pro-256k-250115',
      'qwen-3.0',
      'qwen-max',
      'qwen-max-latest',
      'qwen3-max',
      'deepseek-v3',
      'deepseek-v3-2-251201',
      'glm-4.5',
      'glm-4.5-flash',
      'kimi-k2',
      'moonshot-v1-auto',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'agent-capable',
    name: 'Agent 能力',
    description: '支持复杂 Agent 任务，包括工具调用、多步推理、任务编排',
    category: 'agent',
    priority: 85,
    requiredModels: [
      'claude-sonnet-4-20250514',
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-5-20251101',
      'gpt-4o',
      'gpt-4.1',
      'gpt-5',
      'o3',
      'o4-mini',
      'kimi-k2',
      'deepseek-v3-2-251201',
      'qwen-max-latest',
      'glm-4.5',
    ],
    requiresFunctionCalling: true,
    isBuiltin: true,
  },
  {
    tagId: 'function-calling',
    name: '函数调用',
    description: '支持函数/工具调用能力',
    category: 'agent',
    priority: 80,
    requiredModels: [
      'gpt-4o',
      'gpt-4o-mini',
      'gpt-4.1',
      'gpt-5',
      'claude-sonnet-4-20250514',
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-5-20251101',
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'deepseek-v3-2-251201',
      'qwen-max-latest',
      'qwen-plus-latest',
      'doubao-1-5-pro-32k-250115',
      'glm-4.5',
      'kimi-k2',
      'moonshot-v1-auto',
    ],
    requiresFunctionCalling: true,
    isBuiltin: true,
  },
  {
    tagId: 'fast-response',
    name: '快速响应',
    description: '低延迟响应，适合实时交互场景',
    category: 'performance',
    priority: 75,
    requiredModels: [
      'gpt-4o-mini',
      'gpt-4.1-mini',
      'gpt-4.1-nano',
      'claude-haiku-3-5-20241022',
      'claude-haiku-4-5-20251001',
      'gemini-2.5-flash',
      'glm-4-flash',
      'glm-4.5-air',
      'qwen-turbo-latest',
      'moonshot-v1-8k',
      'doubao-1.5-lite',
    ],
    maxLatencyMs: 3000,
    isBuiltin: true,
  },
  {
    tagId: 'premium',
    name: '旗舰模型',
    description: '最强能力的旗舰模型，适合关键任务',
    category: 'tier',
    priority: 95,
    requiredModels: [
      'claude-opus-4-5-20251101',
      'claude-opus-4-6',
      'gpt-4.5-preview',
      'gpt-5-pro',
      'gpt-5.2-pro',
      'o3',
      'gemini-2.5-pro',
      'gemini-3-pro-preview',
      'grok-4',
      'deepseek-r1',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'general-purpose',
    name: '通用模型',
    description: '综合能力均衡的通用模型',
    category: 'tier',
    priority: 50,
    requiredModels: [
      'gpt-4o',
      'gpt-4.1',
      'claude-sonnet-4-20250514',
      'claude-sonnet-4-5-20250929',
      'gemini-2.5-pro',
      'deepseek-v3-2-251201',
      'qwen-max-latest',
      'doubao-1.5-pro-256k-250115',
      'glm-4.5',
      'kimi-k2',
    ],
    isBuiltin: true,
  },
  {
    tagId: 'multimodal',
    name: '多模态',
    description: '支持多种模态输入输出（文本、图像、音频、视频）',
    category: 'modality',
    priority: 70,
    requiredModels: [
      'gpt-4o',
      'gpt-4.1',
      'gpt-5',
      'gemini-2.5-pro',
      'gemini-3-pro-preview',
      'claude-sonnet-4-5-20250929',
      'claude-opus-4-5-20251101',
      'qwen-vl-max-latest',
      'qvq-max',
      'doubao-1.5-vision-pro-32k',
      'doubao-seed-1-6-vision',
    ],
    requiresVision: true,
    isBuiltin: true,
  },
  {
    tagId: 'math-optimized',
    name: '数学优化',
    description: '数学计算和推理能力优化',
    category: 'reasoning',
    priority: 65,
    requiredModels: [
      'o3',
      'o4-mini',
      'deepseek-r1',
      'qwen-qwq-plus',
      'qwen-math-plus',
      'gemini-2.5-pro',
      'claude-opus-4-5-20251101',
    ],
    isBuiltin: true,
  },
];
