/**
 * Channel Definitions Data
 * 渠道定义数据 - 用于数据库 seed
 */

export interface ChannelCredentialFieldData {
  key: string;
  label: string;
  placeholder: string;
  fieldType: 'text' | 'password';
  required: boolean;
  sortOrder: number;
}

export interface ChannelDefinitionData {
  id: string;
  label: string;
  icon: string;
  popular: boolean;
  tokenHint: string;
  tokenPlaceholder: string;
  helpUrl?: string;
  helpText?: string;
  sortOrder: number;
  credentials: ChannelCredentialFieldData[];
}

export const CHANNEL_DEFINITIONS: ChannelDefinitionData[] = [
  // Popular channels
  {
    id: 'feishu',
    label: '飞书/Lark',
    icon: '🪶',
    popular: true,
    tokenHint: '从飞书开放平台获取 Bot App ID 和 App Secret',
    tokenPlaceholder: 'cli_xxx...',
    helpUrl: 'https://open.feishu.cn/document/home/develop-a-bot-in-5-minutes/create-an-app',
    helpText: '飞书开放平台 - 创建应用',
    sortOrder: 1,
    credentials: [
      { key: 'appId', label: 'App ID', placeholder: 'cli_xxx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'appSecret', label: 'App Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'telegram',
    label: 'Telegram',
    icon: 'TG',
    popular: true,
    tokenHint: 'Get this from @BotFather on Telegram',
    tokenPlaceholder: '123456:ABC-DEF...',
    helpUrl: 'https://core.telegram.org/bots/tutorial#obtain-your-bot-token',
    helpText: 'Telegram Bot API - 获取 Bot Token',
    sortOrder: 2,
    credentials: [
      { key: 'botToken', label: 'Bot Token', placeholder: '123456:ABC-DEF...', fieldType: 'password', required: true, sortOrder: 1 },
    ],
  },
  {
    id: 'discord',
    label: 'Discord',
    icon: 'DC',
    popular: true,
    tokenHint: 'Get this from Discord Developer Portal',
    tokenPlaceholder: 'MTA2...',
    helpUrl: 'https://discord.com/developers/docs/getting-started',
    helpText: 'Discord Developer Portal - 创建 Bot',
    sortOrder: 3,
    credentials: [
      { key: 'botToken', label: 'Bot Token', placeholder: 'MTA2...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'applicationId', label: 'Application ID', placeholder: '123456789...', fieldType: 'text', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'slack',
    label: 'Slack',
    icon: 'SL',
    popular: true,
    tokenHint: 'Bot User OAuth Token from Slack App settings',
    tokenPlaceholder: 'xoxb-...',
    helpUrl: 'https://api.slack.com/start/quickstart',
    helpText: 'Slack API - 创建 App',
    sortOrder: 4,
    credentials: [
      { key: 'botToken', label: 'Bot Token', placeholder: 'xoxb-...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'appToken', label: 'App Token', placeholder: 'xapp-...', fieldType: 'password', required: false, sortOrder: 2 },
      { key: 'signingSecret', label: 'Signing Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    icon: 'WA',
    popular: true,
    tokenHint: 'WhatsApp Business API access token',
    tokenPlaceholder: 'EAAx...',
    helpUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api/get-started',
    helpText: 'WhatsApp Cloud API - 快速入门',
    sortOrder: 5,
    credentials: [
      { key: 'accessToken', label: 'Access Token', placeholder: 'EAAx...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'phoneNumberId', label: 'Phone Number ID', placeholder: '123456789...', fieldType: 'text', required: true, sortOrder: 2 },
      { key: 'businessAccountId', label: 'Business Account ID', placeholder: '123456789...', fieldType: 'text', required: true, sortOrder: 3 },
    ],
  },
  // Other channels
  {
    id: 'signal',
    label: 'Signal',
    icon: 'SG',
    popular: false,
    tokenHint: 'Signal API credentials',
    tokenPlaceholder: 'signal-...',
    helpUrl: 'https://signal.org/docs/',
    helpText: 'Signal - API 文档',
    sortOrder: 10,
    credentials: [
      { key: 'phoneNumber', label: 'Phone Number', placeholder: '+1234567890', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'apiKey', label: 'API Key', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'matrix',
    label: 'Matrix',
    icon: 'MX',
    popular: false,
    tokenHint: 'Matrix access token for your bot user',
    tokenPlaceholder: 'syt_...',
    helpUrl: 'https://matrix.org/docs/develop/',
    helpText: 'Matrix - 开发文档',
    sortOrder: 11,
    credentials: [
      { key: 'homeserverUrl', label: 'Homeserver URL', placeholder: 'https://matrix.org', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'accessToken', label: 'Access Token', placeholder: 'syt_...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'userId', label: 'User ID', placeholder: '@bot:matrix.org', fieldType: 'text', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'nostr',
    label: 'Nostr',
    icon: 'NS',
    popular: false,
    tokenHint: 'Nostr private key (nsec)',
    tokenPlaceholder: 'nsec1...',
    helpUrl: 'https://nostr.com/',
    helpText: 'Nostr - 协议文档',
    sortOrder: 12,
    credentials: [
      { key: 'privateKey', label: 'Private Key (nsec)', placeholder: 'nsec1...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'relays', label: 'Relay URLs', placeholder: 'wss://relay.damus.io', fieldType: 'text', required: false, sortOrder: 2 },
    ],
  },
  {
    id: 'twitter',
    label: 'Twitter/X',
    icon: 'X',
    popular: false,
    tokenHint: 'Twitter API Bearer Token from Developer Portal',
    tokenPlaceholder: 'AAAAAAA...',
    helpUrl: 'https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api',
    helpText: 'Twitter Developer - API 访问',
    sortOrder: 13,
    credentials: [
      { key: 'apiKey', label: 'API Key', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'apiSecret', label: 'API Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'accessToken', label: 'Access Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 3 },
      { key: 'accessTokenSecret', label: 'Access Token Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 4 },
    ],
  },
  {
    id: 'facebook',
    label: 'Facebook Messenger',
    icon: 'FB',
    popular: false,
    tokenHint: 'Facebook Page Access Token',
    tokenPlaceholder: 'EAAx...',
    helpUrl: 'https://developers.facebook.com/docs/messenger-platform/getting-started',
    helpText: 'Facebook Messenger - 快速入门',
    sortOrder: 14,
    credentials: [
      { key: 'pageAccessToken', label: 'Page Access Token', placeholder: 'EAAx...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'appSecret', label: 'App Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'verifyToken', label: 'Verify Token', placeholder: 'your_verify_token', fieldType: 'text', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'instagram',
    label: 'Instagram',
    icon: 'IG',
    popular: false,
    tokenHint: 'Instagram API access token',
    tokenPlaceholder: 'IGQ...',
    helpUrl: 'https://developers.facebook.com/docs/instagram-api/getting-started',
    helpText: 'Instagram API - 快速入门',
    sortOrder: 15,
    credentials: [
      { key: 'accessToken', label: 'Access Token', placeholder: 'IGQ...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'appSecret', label: 'App Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'teams',
    label: 'Microsoft Teams',
    icon: 'MS',
    popular: false,
    tokenHint: 'Microsoft Bot Framework credentials',
    tokenPlaceholder: 'Bot Framework App ID...',
    helpUrl: 'https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams',
    helpText: 'Microsoft Teams - 创建 Bot',
    sortOrder: 16,
    credentials: [
      { key: 'appId', label: 'App ID', placeholder: 'xxx-xxx-xxx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'appPassword', label: 'App Password', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'tenantId', label: 'Tenant ID', placeholder: 'xxx-xxx-xxx...', fieldType: 'text', required: false, sortOrder: 3 },
    ],
  },
  {
    id: 'line',
    label: 'LINE',
    icon: 'LN',
    popular: false,
    tokenHint: 'LINE Channel Access Token',
    tokenPlaceholder: 'Bearer token...',
    helpUrl: 'https://developers.line.biz/en/docs/messaging-api/getting-started/',
    helpText: 'LINE Messaging API - 快速入门',
    sortOrder: 17,
    credentials: [
      { key: 'channelAccessToken', label: 'Channel Access Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'channelSecret', label: 'Channel Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'wechat',
    label: 'WeChat',
    icon: 'WC',
    popular: false,
    tokenHint: 'WeChat Official Account access token',
    tokenPlaceholder: 'Access token...',
    helpUrl: 'https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Overview.html',
    helpText: '微信公众平台 - 开发文档',
    sortOrder: 18,
    credentials: [
      { key: 'appId', label: 'App ID', placeholder: 'wx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'appSecret', label: 'App Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'token', label: 'Token', placeholder: 'your_token', fieldType: 'text', required: true, sortOrder: 3 },
      { key: 'encodingAESKey', label: 'Encoding AES Key', placeholder: 'xxx...', fieldType: 'password', required: false, sortOrder: 4 },
    ],
  },
  {
    id: 'viber',
    label: 'Viber',
    icon: 'VB',
    popular: false,
    tokenHint: 'Viber Bot API authentication token',
    tokenPlaceholder: 'Auth token...',
    helpUrl: 'https://developers.viber.com/docs/api/rest-bot-api/',
    helpText: 'Viber Bot API - 文档',
    sortOrder: 19,
    credentials: [
      { key: 'authToken', label: 'Auth Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 1 },
    ],
  },
  {
    id: 'kik',
    label: 'Kik',
    icon: 'KK',
    popular: false,
    tokenHint: 'Kik Bot API key',
    tokenPlaceholder: 'API key...',
    helpUrl: 'https://dev.kik.com/',
    helpText: 'Kik Developer - 文档',
    sortOrder: 20,
    credentials: [
      { key: 'username', label: 'Bot Username', placeholder: 'your_bot', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'apiKey', label: 'API Key', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'twitch',
    label: 'Twitch',
    icon: 'TW',
    popular: false,
    tokenHint: 'Twitch OAuth token from Developer Console',
    tokenPlaceholder: 'oauth:...',
    helpUrl: 'https://dev.twitch.tv/docs/irc/',
    helpText: 'Twitch IRC - 文档',
    sortOrder: 21,
    credentials: [
      { key: 'clientId', label: 'Client ID', placeholder: 'xxx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'clientSecret', label: 'Client Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'oauthToken', label: 'OAuth Token', placeholder: 'oauth:xxx...', fieldType: 'password', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'reddit',
    label: 'Reddit',
    icon: 'RD',
    popular: false,
    tokenHint: 'Reddit API credentials (client_id:secret)',
    tokenPlaceholder: 'client_id:client_secret',
    helpUrl: 'https://www.reddit.com/wiki/api/',
    helpText: 'Reddit API - 文档',
    sortOrder: 22,
    credentials: [
      { key: 'clientId', label: 'Client ID', placeholder: 'xxx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'clientSecret', label: 'Client Secret', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'username', label: 'Username', placeholder: 'your_bot', fieldType: 'text', required: true, sortOrder: 3 },
      { key: 'password', label: 'Password', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 4 },
    ],
  },
  {
    id: 'mastodon',
    label: 'Mastodon',
    icon: 'MD',
    popular: false,
    tokenHint: 'Mastodon access token from your instance',
    tokenPlaceholder: 'Access token...',
    helpUrl: 'https://docs.joinmastodon.org/client/intro/',
    helpText: 'Mastodon API - 文档',
    sortOrder: 23,
    credentials: [
      { key: 'instanceUrl', label: 'Instance URL', placeholder: 'https://mastodon.social', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'accessToken', label: 'Access Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'bluesky',
    label: 'Bluesky',
    icon: 'BS',
    popular: false,
    tokenHint: 'Bluesky App Password',
    tokenPlaceholder: 'xxxx-xxxx-xxxx-xxxx',
    helpUrl: 'https://atproto.com/guides/applications',
    helpText: 'AT Protocol - 应用开发',
    sortOrder: 24,
    credentials: [
      { key: 'handle', label: 'Handle', placeholder: 'your.bsky.social', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'appPassword', label: 'App Password', placeholder: 'xxxx-xxxx-xxxx-xxxx', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'rocketchat',
    label: 'Rocket.Chat',
    icon: 'RC',
    popular: false,
    tokenHint: 'Rocket.Chat Personal Access Token',
    tokenPlaceholder: 'Token...',
    helpUrl: 'https://developer.rocket.chat/reference/api/rest-api',
    helpText: 'Rocket.Chat API - 文档',
    sortOrder: 25,
    credentials: [
      { key: 'serverUrl', label: 'Server URL', placeholder: 'https://your.rocket.chat', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'userId', label: 'User ID', placeholder: 'xxx...', fieldType: 'text', required: true, sortOrder: 2 },
      { key: 'authToken', label: 'Auth Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'mattermost',
    label: 'Mattermost',
    icon: 'MM',
    popular: false,
    tokenHint: 'Mattermost Bot Access Token',
    tokenPlaceholder: 'Bot token...',
    helpUrl: 'https://developers.mattermost.com/integrate/reference/bot-accounts/',
    helpText: 'Mattermost - Bot 账户',
    sortOrder: 26,
    credentials: [
      { key: 'serverUrl', label: 'Server URL', placeholder: 'https://your.mattermost.com', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'botToken', label: 'Bot Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'zulip',
    label: 'Zulip',
    icon: 'ZU',
    popular: false,
    tokenHint: 'Zulip Bot API key',
    tokenPlaceholder: 'API key...',
    helpUrl: 'https://zulip.com/api/running-bots',
    helpText: 'Zulip - Bot 开发',
    sortOrder: 27,
    credentials: [
      { key: 'siteUrl', label: 'Site URL', placeholder: 'https://your.zulipchat.com', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'botEmail', label: 'Bot Email', placeholder: 'bot@your.zulipchat.com', fieldType: 'text', required: true, sortOrder: 2 },
      { key: 'apiKey', label: 'API Key', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'irc',
    label: 'IRC',
    icon: 'IR',
    popular: false,
    tokenHint: 'IRC server password (optional)',
    tokenPlaceholder: 'Password (optional)...',
    helpUrl: 'https://libera.chat/guides/connect',
    helpText: 'IRC - 连接指南',
    sortOrder: 28,
    credentials: [
      { key: 'server', label: 'Server', placeholder: 'irc.libera.chat', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'port', label: 'Port', placeholder: '6697', fieldType: 'text', required: true, sortOrder: 2 },
      { key: 'nickname', label: 'Nickname', placeholder: 'your_bot', fieldType: 'text', required: true, sortOrder: 3 },
      { key: 'password', label: 'Password', placeholder: 'xxx...', fieldType: 'password', required: false, sortOrder: 4 },
    ],
  },
  {
    id: 'xmpp',
    label: 'XMPP/Jabber',
    icon: 'XM',
    popular: false,
    tokenHint: 'XMPP password for bot account',
    tokenPlaceholder: 'Password...',
    helpUrl: 'https://xmpp.org/getting-started/',
    helpText: 'XMPP - 入门指南',
    sortOrder: 29,
    credentials: [
      { key: 'jid', label: 'JID', placeholder: 'bot@xmpp.org', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'password', label: 'Password', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'host', label: 'Host', placeholder: 'xmpp.org', fieldType: 'text', required: false, sortOrder: 3 },
    ],
  },
  {
    id: 'sms',
    label: 'SMS (Twilio)',
    icon: 'SM',
    popular: false,
    tokenHint: 'Twilio Auth Token',
    tokenPlaceholder: 'Auth token...',
    helpUrl: 'https://www.twilio.com/docs/sms/quickstart',
    helpText: 'Twilio SMS - 快速入门',
    sortOrder: 30,
    credentials: [
      { key: 'accountSid', label: 'Account SID', placeholder: 'ACxxx...', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'authToken', label: 'Auth Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 2 },
      { key: 'phoneNumber', label: 'Phone Number', placeholder: '+1234567890', fieldType: 'text', required: true, sortOrder: 3 },
    ],
  },
  {
    id: 'email',
    label: 'Email',
    icon: 'EM',
    popular: false,
    tokenHint: 'SMTP/IMAP credentials',
    tokenPlaceholder: 'Password...',
    helpUrl: 'https://support.google.com/mail/answer/7126229',
    helpText: 'Gmail IMAP/SMTP - 设置',
    sortOrder: 31,
    credentials: [
      { key: 'smtpHost', label: 'SMTP Host', placeholder: 'smtp.gmail.com', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'smtpPort', label: 'SMTP Port', placeholder: '587', fieldType: 'text', required: true, sortOrder: 2 },
      { key: 'imapHost', label: 'IMAP Host', placeholder: 'imap.gmail.com', fieldType: 'text', required: true, sortOrder: 3 },
      { key: 'imapPort', label: 'IMAP Port', placeholder: '993', fieldType: 'text', required: true, sortOrder: 4 },
      { key: 'email', label: 'Email', placeholder: 'bot@example.com', fieldType: 'text', required: true, sortOrder: 5 },
      { key: 'password', label: 'Password', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 6 },
    ],
  },
  {
    id: 'googlechat',
    label: 'Google Chat',
    icon: 'GC',
    popular: false,
    tokenHint: 'Google Cloud service account JSON key',
    tokenPlaceholder: 'Service account key...',
    helpUrl: 'https://developers.google.com/chat/quickstart/gcf-app',
    helpText: 'Google Chat API - 快速入门',
    sortOrder: 32,
    credentials: [
      { key: 'serviceAccountKey', label: 'Service Account Key (JSON)', placeholder: '{"type": "service_account"...}', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'projectId', label: 'Project ID', placeholder: 'your-project-id', fieldType: 'text', required: true, sortOrder: 2 },
    ],
  },
  {
    id: 'webex',
    label: 'Webex',
    icon: 'WX',
    popular: false,
    tokenHint: 'Webex Bot Access Token',
    tokenPlaceholder: 'Access token...',
    helpUrl: 'https://developer.webex.com/docs/bots',
    helpText: 'Webex - Bot 开发',
    sortOrder: 33,
    credentials: [
      { key: 'accessToken', label: 'Access Token', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 1 },
    ],
  },
  {
    id: 'web',
    label: 'Web Chat',
    icon: 'WB',
    popular: false,
    tokenHint: 'API key for web widget authentication',
    tokenPlaceholder: 'API key...',
    helpText: 'Web Chat - 配置',
    sortOrder: 34,
    credentials: [
      { key: 'apiKey', label: 'API Key', placeholder: 'xxx...', fieldType: 'password', required: true, sortOrder: 1 },
      { key: 'allowedOrigins', label: 'Allowed Origins', placeholder: 'https://example.com', fieldType: 'text', required: false, sortOrder: 2 },
    ],
  },
  {
    id: 'webhook',
    label: 'Webhook',
    icon: 'WH',
    popular: false,
    tokenHint: 'Webhook secret for request validation',
    tokenPlaceholder: 'Secret...',
    helpText: 'Webhook - 配置',
    sortOrder: 35,
    credentials: [
      { key: 'webhookUrl', label: 'Webhook URL', placeholder: 'https://your-server.com/webhook', fieldType: 'text', required: true, sortOrder: 1 },
      { key: 'secret', label: 'Secret', placeholder: 'xxx...', fieldType: 'password', required: false, sortOrder: 2 },
    ],
  },
];
