/**
 * AI 模型定价与能力数据
 * 价格单位：美元/百万 tokens (LLM) 或 美元/次 (图像/视频)
 * 数据来源：各 AI 服务商官方定价页面
 * 最后更新：2026-02-10
 */

export interface ModelCatalogData {
  model: string;
  vendor: string;
  inputPrice: number;
  outputPrice: number;
  displayName?: string;
  description?: string;
  notes?: string;
  cacheReadPrice?: number;
  cacheWritePrice?: number;
  thinkingPrice?: number;
  reasoningScore?: number;
  codingScore?: number;
  creativityScore?: number;
  speedScore?: number;
  contextLength?: number;
  supportsExtendedThinking?: boolean;
  supportsCacheControl?: boolean;
  supportsVision?: boolean;
  supportsFunctionCalling?: boolean;
  supportsStreaming?: boolean;
  modelType?: 'llm' | 'vlm' | 'image' | 'video' | 'audio' | 'embedding' | '3d';
  recommendedScenarios?: string[];
}

export const MODEL_CATALOG_DATA: ModelCatalogData[] = [
  // ============================================================================
  // OpenAI Models - GPT-4o Series
  // ============================================================================
  {
    model: 'gpt-4o',
    vendor: 'openai',
    inputPrice: 2.5,
    outputPrice: 10,
    displayName: 'GPT-4o',
    reasoningScore: 90,
    codingScore: 92,
    creativityScore: 88,
    speedScore: 85,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['general-purpose', 'multimodal', 'coding'],
  },
  {
    model: 'gpt-4o-2024-08-06',
    vendor: 'openai',
    inputPrice: 2.5,
    outputPrice: 10,
    displayName: 'GPT-4o (2024-08-06)',
  },
  {
    model: 'gpt-4o-mini',
    vendor: 'openai',
    inputPrice: 0.15,
    outputPrice: 0.6,
    displayName: 'GPT-4o Mini',
    reasoningScore: 75,
    codingScore: 78,
    creativityScore: 72,
    speedScore: 95,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  {
    model: 'gpt-4o-mini-2024-07-18',
    vendor: 'openai',
    inputPrice: 0.15,
    outputPrice: 0.6,
    displayName: 'GPT-4o Mini (2024-07-18)',
  },
  {
    model: 'gpt-4o-mini-tts',
    vendor: 'openai',
    inputPrice: 0.6,
    outputPrice: 2.4,
    displayName: 'GPT-4o Mini TTS',
    modelType: 'audio',
  },
  {
    model: 'gpt-4o-transcribe',
    vendor: 'openai',
    inputPrice: 2.5,
    outputPrice: 10,
    displayName: 'GPT-4o Transcribe',
    modelType: 'audio',
  },
  {
    model: 'gpt-4o-image-vip',
    vendor: 'openai',
    inputPrice: 5,
    outputPrice: 20,
    displayName: 'GPT-4o Image VIP',
    supportsVision: true,
  },
  {
    model: 'chatgpt-4o-latest',
    vendor: 'openai',
    inputPrice: 5,
    outputPrice: 15,
    displayName: 'ChatGPT-4o Latest',
  },
  // OpenAI GPT-4.1 Series
  {
    model: 'gpt-4.1',
    vendor: 'openai',
    inputPrice: 2,
    outputPrice: 8,
    displayName: 'GPT-4.1',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 90,
    speedScore: 88,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['general-purpose', 'coding'],
  },
  {
    model: 'gpt-4.1-2025-04-14',
    vendor: 'openai',
    inputPrice: 2,
    outputPrice: 8,
    displayName: 'GPT-4.1 (2025-04-14)',
  },
  {
    model: 'gpt-4.1-mini',
    vendor: 'openai',
    inputPrice: 0.4,
    outputPrice: 1.6,
    displayName: 'GPT-4.1 Mini',
    reasoningScore: 80,
    codingScore: 82,
    speedScore: 92,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-4.1-mini-2025-04-14',
    vendor: 'openai',
    inputPrice: 0.4,
    outputPrice: 1.6,
    displayName: 'GPT-4.1 Mini (2025-04-14)',
  },
  {
    model: 'gpt-4.1-nano',
    vendor: 'openai',
    inputPrice: 0.1,
    outputPrice: 0.4,
    displayName: 'GPT-4.1 Nano',
    speedScore: 98,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // OpenAI GPT-5 Series
  {
    model: 'gpt-5',
    vendor: 'openai',
    inputPrice: 5,
    outputPrice: 20,
    displayName: 'GPT-5',
    reasoningScore: 96,
    codingScore: 97,
    creativityScore: 94,
    speedScore: 80,
    contextLength: 256,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'complex-tasks'],
  },
  {
    model: 'gpt-5-chat',
    vendor: 'openai',
    inputPrice: 5,
    outputPrice: 20,
    displayName: 'GPT-5 Chat',
  },
  {
    model: 'gpt-5-codex',
    vendor: 'openai',
    inputPrice: 6,
    outputPrice: 24,
    displayName: 'GPT-5 Codex',
    codingScore: 99,
    recommendedScenarios: ['coding', 'code-generation'],
  },
  {
    model: 'gpt-5-mini',
    vendor: 'openai',
    inputPrice: 1,
    outputPrice: 4,
    displayName: 'GPT-5 Mini',
    reasoningScore: 88,
    codingScore: 90,
    speedScore: 90,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-5-nano',
    vendor: 'openai',
    inputPrice: 0.25,
    outputPrice: 1,
    displayName: 'GPT-5 Nano',
    speedScore: 96,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-5-pro',
    vendor: 'openai',
    inputPrice: 10,
    outputPrice: 40,
    displayName: 'GPT-5 Pro',
    reasoningScore: 98,
    codingScore: 98,
    creativityScore: 96,
    contextLength: 256,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-5.1',
    vendor: 'openai',
    inputPrice: 6,
    outputPrice: 24,
    displayName: 'GPT-5.1',
    reasoningScore: 97,
    codingScore: 98,
    creativityScore: 95,
    speedScore: 82,
    contextLength: 256,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-5.1-codex',
    vendor: 'openai',
    inputPrice: 7,
    outputPrice: 28,
    displayName: 'GPT-5.1 Codex',
    codingScore: 99,
  },
  {
    model: 'gpt-5.1-codex-max',
    vendor: 'openai',
    inputPrice: 15,
    outputPrice: 60,
    displayName: 'GPT-5.1 Codex Max',
    codingScore: 100,
  },
  {
    model: 'gpt-5.2',
    vendor: 'openai',
    inputPrice: 8,
    outputPrice: 32,
    displayName: 'GPT-5.2',
    reasoningScore: 98,
    codingScore: 99,
    creativityScore: 96,
    speedScore: 85,
    contextLength: 512,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gpt-5.2-2025-12-11',
    vendor: 'openai',
    inputPrice: 8,
    outputPrice: 32,
    displayName: 'GPT-5.2 (2025-12-11)',
  },
  {
    model: 'gpt-5.2-chat-latest',
    vendor: 'openai',
    inputPrice: 8,
    outputPrice: 32,
    displayName: 'GPT-5.2 Chat Latest',
  },
  {
    model: 'gpt-5.2-codex',
    vendor: 'openai',
    inputPrice: 10,
    outputPrice: 40,
    displayName: 'GPT-5.2 Codex',
    codingScore: 100,
  },
  {
    model: 'gpt-5.2-pro',
    vendor: 'openai',
    inputPrice: 15,
    outputPrice: 60,
    displayName: 'GPT-5.2 Pro',
    reasoningScore: 99,
    codingScore: 100,
  },
  {
    model: 'gpt-5.2-pro-2025-12-11',
    vendor: 'openai',
    inputPrice: 15,
    outputPrice: 60,
    displayName: 'GPT-5.2 Pro (2025-12-11)',
  },
  // OpenAI GPT-4.5 Preview
  {
    model: 'gpt-4.5-preview',
    vendor: 'openai',
    inputPrice: 75,
    outputPrice: 150,
    displayName: 'GPT-4.5 Preview',
    reasoningScore: 99,
    codingScore: 98,
    creativityScore: 98,
    speedScore: 50,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'creative', 'complex-tasks'],
  },
  // OpenAI o-Series (Reasoning)
  {
    model: 'o3',
    vendor: 'openai',
    inputPrice: 10,
    outputPrice: 40,
    displayName: 'o3',
    reasoningScore: 99,
    codingScore: 97,
    speedScore: 60,
    contextLength: 200,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'math', 'science'],
  },
  {
    model: 'o4-mini',
    vendor: 'openai',
    inputPrice: 1.5,
    outputPrice: 6,
    displayName: 'o4 Mini',
    reasoningScore: 92,
    codingScore: 93,
    speedScore: 85,
    contextLength: 200,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['reasoning', 'cost-optimized'],
  },
  // OpenAI Image Models
  {
    model: 'gpt-image-1',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 40,
    displayName: 'GPT Image 1',
    modelType: 'image',
    creativityScore: 95,
    recommendedScenarios: ['image-generation'],
  },
  {
    model: 'gpt-image-1-mini',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 20,
    displayName: 'GPT Image 1 Mini',
    modelType: 'image',
  },
  {
    model: 'gpt-image-1.5',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 50,
    displayName: 'GPT Image 1.5',
    modelType: 'image',
    creativityScore: 97,
  },
  {
    model: 'gpt-image-1.5-plus',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 80,
    displayName: 'GPT Image 1.5 Plus',
    modelType: 'image',
    creativityScore: 98,
  },
  // ============================================================================
  // Anthropic Models
  // ============================================================================
  {
    model: 'claude-opus-4-5-20251101',
    vendor: 'anthropic',
    inputPrice: 15,
    outputPrice: 75,
    cacheReadPrice: 1.5,
    cacheWritePrice: 18.75,
    thinkingPrice: 15,
    displayName: 'Claude Opus 4.5',
    reasoningScore: 100,
    codingScore: 99,
    creativityScore: 97,
    speedScore: 55,
    contextLength: 200,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'complex-analysis', 'research'],
  },
  {
    model: 'claude-opus-4-6',
    vendor: 'anthropic',
    inputPrice: 18,
    outputPrice: 90,
    cacheReadPrice: 1.8,
    cacheWritePrice: 22.5,
    thinkingPrice: 18,
    displayName: 'Claude Opus 4.6',
    reasoningScore: 100,
    codingScore: 100,
    creativityScore: 98,
    speedScore: 50,
    contextLength: 200,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'claude-opus-4-1-20250805',
    vendor: 'anthropic',
    inputPrice: 15,
    outputPrice: 75,
    cacheReadPrice: 1.5,
    cacheWritePrice: 18.75,
    thinkingPrice: 15,
    displayName: 'Claude Opus 4.1',
    reasoningScore: 100,
    codingScore: 98,
    creativityScore: 96,
    speedScore: 58,
    contextLength: 200,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'claude-opus-4-1-20250805-thinking',
    vendor: 'anthropic',
    inputPrice: 15,
    outputPrice: 75,
    thinkingPrice: 15,
    displayName: 'Claude Opus 4.1 Thinking',
    supportsExtendedThinking: true,
  },
  {
    model: 'claude-sonnet-4-5-20250929',
    vendor: 'anthropic',
    inputPrice: 3,
    outputPrice: 15,
    cacheReadPrice: 0.3,
    cacheWritePrice: 3.75,
    thinkingPrice: 3,
    displayName: 'Claude Sonnet 4.5',
    reasoningScore: 94,
    codingScore: 96,
    creativityScore: 92,
    speedScore: 78,
    contextLength: 200,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['coding', 'general-purpose'],
  },
  {
    model: 'claude-sonnet-4-5-20250929-thinking',
    vendor: 'anthropic',
    inputPrice: 3,
    outputPrice: 15,
    thinkingPrice: 3,
    displayName: 'Claude Sonnet 4.5 Thinking',
    supportsExtendedThinking: true,
  },
  {
    model: 'claude-sonnet-4-20250514',
    vendor: 'anthropic',
    inputPrice: 3,
    outputPrice: 15,
    cacheReadPrice: 0.3,
    cacheWritePrice: 3.75,
    thinkingPrice: 3,
    displayName: 'Claude Sonnet 4',
    reasoningScore: 92,
    codingScore: 95,
    creativityScore: 90,
    speedScore: 80,
    contextLength: 200,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'claude-sonnet-4-20250514-thinking',
    vendor: 'anthropic',
    inputPrice: 3,
    outputPrice: 15,
    thinkingPrice: 3,
    displayName: 'Claude Sonnet 4 Thinking',
    supportsExtendedThinking: true,
  },
  {
    model: 'claude-haiku-4-5-20251001',
    vendor: 'anthropic',
    inputPrice: 0.8,
    outputPrice: 4,
    cacheReadPrice: 0.08,
    cacheWritePrice: 1,
    displayName: 'Claude Haiku 4.5',
    reasoningScore: 78,
    codingScore: 82,
    creativityScore: 75,
    speedScore: 96,
    contextLength: 200,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'high-volume'],
  },
  {
    model: 'claude-haiku-3-5-20241022',
    vendor: 'anthropic',
    inputPrice: 0.25,
    outputPrice: 1.25,
    cacheReadPrice: 0.03,
    cacheWritePrice: 0.3,
    displayName: 'Claude Haiku 3.5',
    reasoningScore: 72,
    codingScore: 75,
    creativityScore: 70,
    speedScore: 98,
    contextLength: 200,
    supportsCacheControl: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  // ============================================================================
  // DeepSeek Models
  // ============================================================================
  {
    model: 'deepseek-v3',
    vendor: 'deepseek',
    inputPrice: 0.27,
    outputPrice: 1.1,
    displayName: 'DeepSeek V3',
    reasoningScore: 88,
    codingScore: 94,
    creativityScore: 82,
    speedScore: 88,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['cost-optimized', 'coding'],
  },
  {
    model: 'deepseek-v3-2-251201',
    vendor: 'deepseek',
    inputPrice: 0.27,
    outputPrice: 1.1,
    displayName: 'DeepSeek V3.2 (251201)',
    reasoningScore: 92,
    codingScore: 96,
    creativityScore: 86,
    speedScore: 88,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'deepseek-chat',
    vendor: 'deepseek',
    inputPrice: 0.27,
    outputPrice: 1.1,
    displayName: 'DeepSeek Chat',
    reasoningScore: 88,
    codingScore: 94,
    speedScore: 88,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'deepseek-r1',
    vendor: 'deepseek',
    inputPrice: 0.55,
    outputPrice: 2.19,
    displayName: 'DeepSeek R1',
    reasoningScore: 96,
    codingScore: 95,
    creativityScore: 80,
    speedScore: 65,
    contextLength: 64,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'math', 'coding'],
  },
  {
    model: 'deepseek-reasoner',
    vendor: 'deepseek',
    inputPrice: 0.55,
    outputPrice: 2.19,
    displayName: 'DeepSeek Reasoner',
    reasoningScore: 96,
    codingScore: 95,
    speedScore: 65,
    contextLength: 64,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'deepseek-v3-search',
    vendor: 'deepseek',
    inputPrice: 0.35,
    outputPrice: 1.4,
    displayName: 'DeepSeek V3 Search',
    reasoningScore: 88,
    codingScore: 94,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'deepseek-reasoner-search',
    vendor: 'deepseek',
    inputPrice: 0.7,
    outputPrice: 2.8,
    displayName: 'DeepSeek Reasoner Search',
    reasoningScore: 96,
    speedScore: 60,
    contextLength: 64,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // ============================================================================
  // Google Gemini Models
  // ============================================================================
  {
    model: 'gemini-2.0-flash',
    vendor: 'google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    displayName: 'Gemini 2.0 Flash',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 95,
    contextLength: 1000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'multimodal'],
  },
  {
    model: 'gemini-2.5-flash',
    vendor: 'google',
    inputPrice: 0.075,
    outputPrice: 0.3,
    displayName: 'Gemini 2.5 Flash',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 96,
    contextLength: 1000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  {
    model: 'gemini-2.5-flash-nothinking',
    vendor: 'google',
    inputPrice: 0.075,
    outputPrice: 0.3,
    displayName: 'Gemini 2.5 Flash (No Thinking)',
    speedScore: 98,
  },
  {
    model: 'gemini-2.5-flash-image',
    vendor: 'google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    displayName: 'Gemini 2.5 Flash Image',
    modelType: 'vlm',
    supportsVision: true,
  },
  {
    model: 'gemini-2.5-flash-image-hd',
    vendor: 'google',
    inputPrice: 0.15,
    outputPrice: 0.6,
    displayName: 'Gemini 2.5 Flash Image HD',
    modelType: 'vlm',
    supportsVision: true,
  },
  {
    model: 'gemini-2.5-flash-preview-tts',
    vendor: 'google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    displayName: 'Gemini 2.5 Flash TTS',
    modelType: 'audio',
  },
  {
    model: 'gemini-2.5-pro',
    vendor: 'google',
    inputPrice: 1.25,
    outputPrice: 5,
    displayName: 'Gemini 2.5 Pro',
    reasoningScore: 92,
    codingScore: 93,
    creativityScore: 88,
    speedScore: 75,
    contextLength: 2000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['long-context', 'complex-tasks'],
  },
  {
    model: 'gemini-2.5-pro-preview-tts',
    vendor: 'google',
    inputPrice: 1.25,
    outputPrice: 5,
    displayName: 'Gemini 2.5 Pro TTS',
    modelType: 'audio',
  },
  {
    model: 'gemini-3-flash-preview',
    vendor: 'google',
    inputPrice: 0.05,
    outputPrice: 0.2,
    displayName: 'Gemini 3 Flash Preview',
    reasoningScore: 88,
    codingScore: 90,
    speedScore: 97,
    contextLength: 2000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gemini-3-pro-preview',
    vendor: 'google',
    inputPrice: 1,
    outputPrice: 4,
    displayName: 'Gemini 3 Pro Preview',
    reasoningScore: 95,
    codingScore: 96,
    creativityScore: 92,
    speedScore: 78,
    contextLength: 2000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'gemini-3-pro-image-preview',
    vendor: 'google',
    inputPrice: 1.5,
    outputPrice: 6,
    displayName: 'Gemini 3 Pro Image Preview',
    modelType: 'vlm',
    supportsVision: true,
  },
  // Google Veo Video Models
  {
    model: 'veo3',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.5,
    displayName: 'Veo 3',
    modelType: 'video',
    creativityScore: 95,
    recommendedScenarios: ['video-generation'],
  },
  {
    model: 'veo3-fast',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Veo 3 Fast',
    modelType: 'video',
    speedScore: 90,
  },
  {
    model: 'veo3-pro',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 1,
    displayName: 'Veo 3 Pro',
    modelType: 'video',
    creativityScore: 98,
  },
  {
    model: 'veo3.1',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.6,
    displayName: 'Veo 3.1',
    modelType: 'video',
    creativityScore: 96,
  },
  {
    model: 'veo3.1-fast',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.3,
    displayName: 'Veo 3.1 Fast',
    modelType: 'video',
    speedScore: 92,
  },
  {
    model: 'veo3.1-pro',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 1.2,
    displayName: 'Veo 3.1 Pro',
    modelType: 'video',
    creativityScore: 99,
  },
  {
    model: 'veo-3.1-fast-generate-preview',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.3,
    displayName: 'Veo 3.1 Fast Generate Preview',
    modelType: 'video',
  },
  {
    model: 'veo-3.1-generate-preview',
    vendor: 'google',
    inputPrice: 0,
    outputPrice: 0.6,
    displayName: 'Veo 3.1 Generate Preview',
    modelType: 'video',
  },
  // ============================================================================
  // xAI Grok Models
  // ============================================================================
  {
    model: 'grok-3',
    vendor: 'xai',
    inputPrice: 3,
    outputPrice: 15,
    displayName: 'Grok 3',
    reasoningScore: 92,
    codingScore: 90,
    creativityScore: 88,
    speedScore: 80,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['general-purpose', 'reasoning'],
  },
  {
    model: 'grok-3-mini',
    vendor: 'xai',
    inputPrice: 0.3,
    outputPrice: 0.5,
    displayName: 'Grok 3 Mini',
    reasoningScore: 78,
    speedScore: 95,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'grok-3-reasoner',
    vendor: 'xai',
    inputPrice: 5,
    outputPrice: 25,
    displayName: 'Grok 3 Reasoner',
    reasoningScore: 96,
    codingScore: 92,
    speedScore: 60,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'grok-3-reasoner-r',
    vendor: 'xai',
    inputPrice: 5,
    outputPrice: 25,
    displayName: 'Grok 3 Reasoner R',
    reasoningScore: 97,
  },
  {
    model: 'grok-4',
    vendor: 'xai',
    inputPrice: 5,
    outputPrice: 25,
    displayName: 'Grok 4',
    reasoningScore: 96,
    codingScore: 95,
    creativityScore: 92,
    speedScore: 75,
    contextLength: 1000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'long-context'],
  },
  {
    model: 'grok-4-0709',
    vendor: 'xai',
    inputPrice: 5,
    outputPrice: 25,
    displayName: 'Grok 4 (0709)',
  },
  {
    model: 'grok-4-1-fast-non-reasoning',
    vendor: 'xai',
    inputPrice: 2,
    outputPrice: 10,
    displayName: 'Grok 4.1 Fast',
    speedScore: 92,
  },
  {
    model: 'grok-4-1-fast-reasoning',
    vendor: 'xai',
    inputPrice: 3,
    outputPrice: 15,
    displayName: 'Grok 4.1 Fast Reasoning',
    reasoningScore: 94,
  },
  {
    model: 'grok-4-image',
    vendor: 'xai',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Grok 4 Image',
    modelType: 'image',
    creativityScore: 92,
  },
  {
    model: 'grok-2-image',
    vendor: 'xai',
    inputPrice: 0,
    outputPrice: 0.07,
    displayName: 'Grok 2 Image',
    modelType: 'image',
  },
  {
    model: 'grok-code-fast-1',
    vendor: 'xai',
    inputPrice: 1,
    outputPrice: 5,
    displayName: 'Grok Code Fast 1',
    codingScore: 94,
    speedScore: 90,
  },
  {
    model: 'grok-imagine-0.9',
    vendor: 'xai',
    inputPrice: 0,
    outputPrice: 0.06,
    displayName: 'Grok Imagine 0.9',
    modelType: 'image',
  },
  {
    model: 'grok-imagine-image',
    vendor: 'xai',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Grok Imagine Image',
    modelType: 'image',
  },
  // ============================================================================
  // ByteDance Doubao Models
  // ============================================================================
  // Doubao Seed 1.6 Series
  {
    model: 'doubao-seed-1-6',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao Seed 1.6',
    reasoningScore: 88,
    codingScore: 90,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-seed-1-6-251015',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao Seed 1.6 (251015)',
    reasoningScore: 89,
    codingScore: 91,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-seed-1-6-250615',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao Seed 1.6 (250615)',
    reasoningScore: 88,
    codingScore: 90,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-seed-1-6-flash',
    vendor: 'doubao',
    inputPrice: 0.07,
    outputPrice: 0.18,
    displayName: 'Doubao Seed 1.6 Flash',
    speedScore: 95,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-seed-1-6-flash-250615',
    vendor: 'doubao',
    inputPrice: 0.07,
    outputPrice: 0.18,
    displayName: 'Doubao Seed 1.6 Flash (250615)',
    speedScore: 95,
  },
  {
    model: 'doubao-seed-1.6-thinking',
    vendor: 'doubao',
    inputPrice: 0.21,
    outputPrice: 0.56,
    displayName: 'Doubao Seed 1.6 Thinking',
    reasoningScore: 92,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-seed-1-6-thinking-250615',
    vendor: 'doubao',
    inputPrice: 0.21,
    outputPrice: 0.56,
    displayName: 'Doubao Seed 1.6 Thinking (250615)',
    reasoningScore: 92,
    supportsExtendedThinking: true,
  },
  {
    model: 'doubao-seed-1-6-thinking-250715',
    vendor: 'doubao',
    inputPrice: 0.21,
    outputPrice: 0.56,
    displayName: 'Doubao Seed 1.6 Thinking (250715)',
    reasoningScore: 93,
    supportsExtendedThinking: true,
  },
  {
    model: 'doubao-seed-1-6-vision',
    vendor: 'doubao',
    inputPrice: 0.18,
    outputPrice: 0.45,
    displayName: 'Doubao Seed 1.6 Vision',
    modelType: 'vlm',
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // Doubao 1.5 Series
  {
    model: 'doubao-1-5-pro-32k-250115',
    vendor: 'doubao',
    inputPrice: 0.11,
    outputPrice: 0.28,
    displayName: 'Doubao 1.5 Pro 32K',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 88,
    contextLength: 131,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['cost-optimized', 'general-purpose'],
  },
  {
    model: 'doubao-1.5-pro-32k',
    vendor: 'doubao',
    inputPrice: 0.11,
    outputPrice: 0.28,
    displayName: 'Doubao 1.5 Pro 32K',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 88,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-pro-256k',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Pro 256K',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 82,
    contextLength: 256,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-pro-256k-250115',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Pro 256K (250115)',
    reasoningScore: 86,
    codingScore: 89,
    speedScore: 82,
    contextLength: 256,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['long-context', 'chinese-optimized'],
  },
  {
    model: 'doubao-vision-pro-32k',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao Vision Pro 32K',
    modelType: 'vlm',
    reasoningScore: 85,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['multimodal', 'vision'],
  },
  {
    model: 'doubao-1.5-lite',
    vendor: 'doubao',
    inputPrice: 0.04,
    outputPrice: 0.1,
    displayName: 'Doubao 1.5 Lite',
    speedScore: 96,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-character-pro-32k',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Character Pro 32K',
    creativityScore: 90,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-thinking-pro',
    vendor: 'doubao',
    inputPrice: 0.56,
    outputPrice: 1.4,
    displayName: 'Doubao 1.5 Thinking Pro',
    reasoningScore: 92,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-thinking-pro-m',
    vendor: 'doubao',
    inputPrice: 0.28,
    outputPrice: 0.7,
    displayName: 'Doubao 1.5 Thinking Pro M',
    reasoningScore: 90,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-thinking-vision-pro',
    vendor: 'doubao',
    inputPrice: 0.7,
    outputPrice: 1.75,
    displayName: 'Doubao 1.5 Thinking Vision Pro',
    modelType: 'vlm',
    reasoningScore: 92,
    supportsVision: true,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1-5-vision-pro-32k-250115',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Vision Pro 32K',
    modelType: 'vlm',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    model: 'doubao-1.5-vision-pro-32k',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Vision Pro 32K',
    modelType: 'vlm',
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-vision-lite',
    vendor: 'doubao',
    inputPrice: 0.04,
    outputPrice: 0.1,
    displayName: 'Doubao 1.5 Vision Lite',
    modelType: 'vlm',
    supportsVision: true,
    speedScore: 95,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1.5-ui-tars',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 UI TARS',
    modelType: 'vlm',
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // Doubao Search Models
  {
    model: 'doubao-1.5-pro-32k-search',
    vendor: 'doubao',
    inputPrice: 0.14,
    outputPrice: 0.35,
    displayName: 'Doubao 1.5 Pro 32K Search',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 85,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'doubao-1-5-thinking-pro-search',
    vendor: 'doubao',
    inputPrice: 0.7,
    outputPrice: 1.75,
    displayName: 'Doubao 1.5 Thinking Pro Search',
    reasoningScore: 92,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // Doubao Embedding Models
  {
    model: 'doubao-embedding',
    vendor: 'doubao',
    inputPrice: 0.05,
    outputPrice: 0,
    displayName: 'Doubao Embedding',
    modelType: 'embedding',
  },
  {
    model: 'doubao-embedding-large',
    vendor: 'doubao',
    inputPrice: 0.07,
    outputPrice: 0,
    displayName: 'Doubao Embedding Large',
    modelType: 'embedding',
  },
  {
    model: 'doubao-embedding-vision',
    vendor: 'doubao',
    inputPrice: 0.1,
    outputPrice: 0,
    displayName: 'Doubao Embedding Vision',
    modelType: 'embedding',
    supportsVision: true,
  },
  // Doubao Classification
  {
    model: 'doubao-clasi',
    vendor: 'doubao',
    inputPrice: 0.04,
    outputPrice: 0.1,
    displayName: 'Doubao Classification',
    speedScore: 98,
  },
  // Doubao Video Models
  {
    model: 'doubao-seedance-1-0-pro',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Doubao Seedance 1.0 Pro',
    modelType: 'video',
    creativityScore: 88,
  },
  {
    model: 'doubao-seedance-1.0-lite',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.06,
    displayName: 'Doubao Seedance 1.0 Lite',
    modelType: 'video',
    speedScore: 92,
  },
  {
    model: 'doubao-seedance-start-scene-1.0-lite',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Doubao Seedance Start Scene 1.0 Lite',
    modelType: 'video',
  },
  {
    model: 'doubao-seedance-1-5-pro-251215',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Doubao Seedance 1.5 Pro',
    modelType: 'video',
    creativityScore: 90,
  },
  {
    model: 'seedance-1-0-pro-250528',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Seedance 1.0 Pro',
    modelType: 'video',
  },
  {
    model: 'seedance-1-5-pro-251215',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Seedance 1.5 Pro',
    modelType: 'video',
  },
  // Doubao Image Models
  {
    model: 'doubao-seedream-3.0-t2i',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.015,
    displayName: 'Doubao Seedream 3.0 T2I',
    modelType: 'image',
    creativityScore: 85,
  },
  {
    model: 'doubao-seedream-4-0-250828',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.02,
    displayName: 'Doubao Seedream 4.0',
    modelType: 'image',
    creativityScore: 88,
  },
  {
    model: 'doubao-seedream-4-5-251128',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.025,
    displayName: 'Doubao Seedream 4.5',
    modelType: 'image',
    creativityScore: 92,
  },
  {
    model: 'seedream-4-0-250828',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.02,
    displayName: 'Seedream 4.0',
    modelType: 'image',
  },
  {
    model: 'seedream-4-5-251128',
    vendor: 'doubao',
    inputPrice: 0,
    outputPrice: 0.025,
    displayName: 'Seedream 4.5',
    modelType: 'image',
  },
  // ============================================================================
  // Alibaba Qwen Models
  // ============================================================================
  {
    model: 'qwen-3.0',
    vendor: 'dashscope',
    inputPrice: 0.7,
    outputPrice: 2.1,
    displayName: 'Qwen 3.0',
    reasoningScore: 90,
    codingScore: 92,
    creativityScore: 88,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-3.0-thinking',
    vendor: 'dashscope',
    inputPrice: 1.4,
    outputPrice: 4.2,
    displayName: 'Qwen 3.0 Thinking',
    reasoningScore: 94,
    codingScore: 93,
    speedScore: 70,
    contextLength: 128,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-max',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen Max',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 88,
    speedScore: 78,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-max-latest',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen Max Latest',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 88,
    speedScore: 78,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-max-2025-01-25',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen Max (2025-01-25)',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 88,
    speedScore: 78,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-max-search',
    vendor: 'dashscope',
    inputPrice: 3.5,
    outputPrice: 10.5,
    displayName: 'Qwen Max Search',
    reasoningScore: 92,
    codingScore: 94,
    speedScore: 75,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-plus',
    vendor: 'dashscope',
    inputPrice: 0.56,
    outputPrice: 1.68,
    displayName: 'Qwen Plus',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-plus-latest',
    vendor: 'dashscope',
    inputPrice: 0.56,
    outputPrice: 1.68,
    displayName: 'Qwen Plus Latest',
    reasoningScore: 85,
    codingScore: 88,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-turbo',
    vendor: 'dashscope',
    inputPrice: 0.28,
    outputPrice: 0.84,
    displayName: 'Qwen Turbo',
    speedScore: 92,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-turbo-latest',
    vendor: 'dashscope',
    inputPrice: 0.28,
    outputPrice: 0.84,
    displayName: 'Qwen Turbo Latest',
    speedScore: 93,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  {
    model: 'qwen-coder-plus-latest',
    vendor: 'dashscope',
    inputPrice: 0.7,
    outputPrice: 2.1,
    displayName: 'Qwen Coder Plus Latest',
    reasoningScore: 88,
    codingScore: 95,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['coding', 'code-generation'],
  },
  {
    model: 'qwen-qwq-plus',
    vendor: 'dashscope',
    inputPrice: 1.4,
    outputPrice: 4.2,
    displayName: 'Qwen QWQ Plus',
    reasoningScore: 94,
    codingScore: 90,
    speedScore: 70,
    contextLength: 128,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['deep-reasoning', 'math'],
  },
  {
    model: 'qwen-math-plus',
    vendor: 'dashscope',
    inputPrice: 0.84,
    outputPrice: 2.52,
    displayName: 'Qwen Math Plus',
    reasoningScore: 92,
    codingScore: 85,
    speedScore: 80,
    contextLength: 64,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['math', 'reasoning'],
  },
  {
    model: 'qwen-long',
    vendor: 'dashscope',
    inputPrice: 0.35,
    outputPrice: 1.05,
    displayName: 'Qwen Long',
    reasoningScore: 85,
    speedScore: 80,
    contextLength: 1000,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-vl-max',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen VL Max',
    modelType: 'vlm',
    reasoningScore: 90,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-vl-max-latest',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen VL Max Latest',
    modelType: 'vlm',
    reasoningScore: 90,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qvq-max',
    vendor: 'dashscope',
    inputPrice: 3.5,
    outputPrice: 10.5,
    displayName: 'QVQ Max',
    modelType: 'vlm',
    reasoningScore: 94,
    supportsVision: true,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwq-plus',
    vendor: 'dashscope',
    inputPrice: 1.4,
    outputPrice: 4.2,
    displayName: 'QWQ Plus',
    reasoningScore: 92,
    supportsExtendedThinking: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen3-max',
    vendor: 'dashscope',
    inputPrice: 2.8,
    outputPrice: 8.4,
    displayName: 'Qwen3 Max',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 88,
    speedScore: 78,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'qwen-image',
    vendor: 'dashscope',
    inputPrice: 0,
    outputPrice: 0.02,
    displayName: 'Qwen Image',
    modelType: 'image',
  },
  {
    model: 'qwen-image-lora',
    vendor: 'dashscope',
    inputPrice: 0,
    outputPrice: 0.03,
    displayName: 'Qwen Image LoRA',
    modelType: 'image',
  },
  {
    model: 'qwen-image-plus',
    vendor: 'dashscope',
    inputPrice: 0,
    outputPrice: 0.04,
    displayName: 'Qwen Image Plus',
    modelType: 'image',
    creativityScore: 90,
  },
  {
    model: 'qwen-image-plus-lora',
    vendor: 'dashscope',
    inputPrice: 0,
    outputPrice: 0.05,
    displayName: 'Qwen Image Plus LoRA',
    modelType: 'image',
  },
  // ============================================================================
  // Kuaishou Kling Video Models
  // ============================================================================
  {
    model: 'kling-v2.1-master',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.35,
    displayName: 'Kling V2.1 Master',
    modelType: 'video',
    creativityScore: 92,
  },
  {
    model: 'kling-v2.1-pro',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Kling V2.1 Pro',
    modelType: 'video',
    creativityScore: 90,
  },
  {
    model: 'kling-v2.1-standard',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Kling V2.1 Standard',
    modelType: 'video',
  },
  {
    model: 'kling-v2.5-turbo-pro',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.2,
    displayName: 'Kling V2.5 Turbo Pro',
    modelType: 'video',
    speedScore: 90,
  },
  {
    model: 'kling-v2.6-pro',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.3,
    displayName: 'Kling V2.6 Pro',
    modelType: 'video',
    creativityScore: 94,
  },
  {
    model: 'kling-v2.6-std',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.18,
    displayName: 'Kling V2.6 Standard',
    modelType: 'video',
  },
  {
    model: 'kling-video-o1-pro',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.4,
    displayName: 'Kling Video O1 Pro',
    modelType: 'video',
    creativityScore: 96,
  },
  {
    model: 'kling-video-o1-std',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Kling Video O1 Standard',
    modelType: 'video',
  },
  {
    model: 'kling-image-o1',
    vendor: 'kling',
    inputPrice: 0,
    outputPrice: 0.03,
    displayName: 'Kling Image O1',
    modelType: 'image',
  },
  // ============================================================================
  // MiniMax Hailuo Video Models
  // ============================================================================
  {
    model: 'hailuo-02-fast',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.1,
    displayName: 'Hailuo 02 Fast',
    modelType: 'video',
    speedScore: 95,
  },
  {
    model: 'hailuo-02-pro',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.2,
    displayName: 'Hailuo 02 Pro',
    modelType: 'video',
    creativityScore: 90,
  },
  {
    model: 'hailuo-02-standard',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Hailuo 02 Standard',
    modelType: 'video',
  },
  {
    model: 'hailuo-2.3-fast',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Hailuo 2.3 Fast',
    modelType: 'video',
    speedScore: 96,
  },
  {
    model: 'hailuo-2.3-pro',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Hailuo 2.3 Pro',
    modelType: 'video',
    creativityScore: 93,
  },
  {
    model: 'hailuo-2.3-standard',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.18,
    displayName: 'Hailuo 2.3 Standard',
    modelType: 'video',
  },
  // MiniMax Audio Models
  {
    model: 'speech-02-hd',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.1,
    displayName: 'Speech 02 HD',
    modelType: 'audio',
  },
  {
    model: 'speech-02-turbo',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.05,
    displayName: 'Speech 02 Turbo',
    modelType: 'audio',
    speedScore: 95,
  },
  {
    model: 'speech-2.5-hd-preview',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Speech 2.5 HD Preview',
    modelType: 'audio',
  },
  {
    model: 'speech-2.5-hd-preview-voice-clone',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Speech 2.5 HD Voice Clone',
    modelType: 'audio',
  },
  {
    model: 'speech-2.5-turbo-preview',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.06,
    displayName: 'Speech 2.5 Turbo Preview',
    modelType: 'audio',
  },
  {
    model: 'speech-2.5-turbo-preview-voice-clone',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Speech 2.5 Turbo Voice Clone',
    modelType: 'audio',
  },
  {
    model: 'speech-2.6-hd',
    vendor: 'minimax',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Speech 2.6 HD',
    modelType: 'audio',
  },
  // ============================================================================
  // OpenAI Sora Video Models
  // ============================================================================
  {
    model: 'sora-2',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 0.5,
    displayName: 'Sora 2',
    modelType: 'video',
    creativityScore: 96,
    recommendedScenarios: ['video-generation', 'creative'],
  },
  {
    model: 'sora-2-pro',
    vendor: 'openai',
    inputPrice: 0,
    outputPrice: 1,
    displayName: 'Sora 2 Pro',
    modelType: 'video',
    creativityScore: 98,
  },
  // ============================================================================
  // Higgsfield Video Models
  // ============================================================================
  {
    model: 'higgsfield-lite',
    vendor: 'higgsfield',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Higgsfield Lite',
    modelType: 'video',
    speedScore: 95,
  },
  {
    model: 'higgsfield-standard',
    vendor: 'higgsfield',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Higgsfield Standard',
    modelType: 'video',
  },
  {
    model: 'higgsfield-turbo',
    vendor: 'higgsfield',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Higgsfield Turbo',
    modelType: 'video',
    creativityScore: 88,
  },
  // ============================================================================
  // Vidu Video Models
  // ============================================================================
  {
    model: 'viduq2',
    vendor: 'vidu',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Vidu Q2',
    modelType: 'video',
  },
  {
    model: 'viduq2-pro',
    vendor: 'vidu',
    inputPrice: 0,
    outputPrice: 0.2,
    displayName: 'Vidu Q2 Pro',
    modelType: 'video',
    creativityScore: 88,
  },
  {
    model: 'viduq2-pro-fast',
    vendor: 'vidu',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Vidu Q2 Pro Fast',
    modelType: 'video',
    speedScore: 92,
  },
  {
    model: 'viduq2-turbo',
    vendor: 'vidu',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Vidu Q2 Turbo',
    modelType: 'video',
    speedScore: 96,
  },
  {
    model: 'viduq3-pro',
    vendor: 'vidu',
    inputPrice: 0,
    outputPrice: 0.25,
    displayName: 'Vidu Q3 Pro',
    modelType: 'video',
    creativityScore: 92,
  },
  // ============================================================================
  // Alibaba Wan Video Models
  // ============================================================================
  {
    model: 'wan-2.2-plus',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Wan 2.2 Plus',
    modelType: 'video',
  },
  {
    model: 'wan-2.5',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.18,
    displayName: 'Wan 2.5',
    modelType: 'video',
    creativityScore: 90,
  },
  {
    model: 'wan-2.6',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.22,
    displayName: 'Wan 2.6',
    modelType: 'video',
    creativityScore: 93,
  },
  // ============================================================================
  // Midjourney Image Models
  // ============================================================================
  {
    model: 'Midjourney',
    vendor: 'midjourney',
    inputPrice: 0,
    outputPrice: 0.04,
    displayName: 'Midjourney',
    modelType: 'image',
    creativityScore: 98,
    recommendedScenarios: ['image-generation', 'creative', 'art'],
  },
  // ============================================================================
  // Flux Image Models
  // ============================================================================
  {
    model: 'flux-kontext-max',
    vendor: 'flux',
    inputPrice: 0,
    outputPrice: 0.08,
    displayName: 'Flux Kontext Max',
    modelType: 'image',
    creativityScore: 95,
  },
  {
    model: 'flux-kontext-pro',
    vendor: 'flux',
    inputPrice: 0,
    outputPrice: 0.05,
    displayName: 'Flux Kontext Pro',
    modelType: 'image',
    creativityScore: 92,
  },
  // ============================================================================
  // Ideogram Image Models
  // ============================================================================
  {
    model: 'ideogram-edit-v3',
    vendor: 'ideogram',
    inputPrice: 0,
    outputPrice: 0.04,
    displayName: 'Ideogram Edit V3',
    modelType: 'image',
  },
  {
    model: 'ideogram-generate-v3',
    vendor: 'ideogram',
    inputPrice: 0,
    outputPrice: 0.04,
    displayName: 'Ideogram Generate V3',
    modelType: 'image',
    creativityScore: 90,
  },
  {
    model: 'ideogram-reframe-v3',
    vendor: 'ideogram',
    inputPrice: 0,
    outputPrice: 0.03,
    displayName: 'Ideogram Reframe V3',
    modelType: 'image',
  },
  {
    model: 'ideogram-remix-v3',
    vendor: 'ideogram',
    inputPrice: 0,
    outputPrice: 0.04,
    displayName: 'Ideogram Remix V3',
    modelType: 'image',
  },
  {
    model: 'ideogram-replace-background-v3',
    vendor: 'ideogram',
    inputPrice: 0,
    outputPrice: 0.03,
    displayName: 'Ideogram Replace BG V3',
    modelType: 'image',
  },
  // ============================================================================
  // NovelAI Image Models
  // ============================================================================
  {
    model: 'nai-diffusion-4-5-curated',
    vendor: 'novelai',
    inputPrice: 0,
    outputPrice: 0.02,
    displayName: 'NAI Diffusion 4.5 Curated',
    modelType: 'image',
  },
  {
    model: 'nai-diffusion-4-5-full',
    vendor: 'novelai',
    inputPrice: 0,
    outputPrice: 0.025,
    displayName: 'NAI Diffusion 4.5 Full',
    modelType: 'image',
    creativityScore: 88,
  },
  // ============================================================================
  // Image Utility Models
  // ============================================================================
  {
    model: 'image-background-remover',
    vendor: 'utility',
    inputPrice: 0,
    outputPrice: 0.01,
    displayName: 'Image Background Remover',
    modelType: 'image',
  },
  {
    model: 'image-upscaler',
    vendor: 'utility',
    inputPrice: 0,
    outputPrice: 0.02,
    displayName: 'Image Upscaler',
    modelType: 'image',
  },
  {
    model: 'image-watermark-remover',
    vendor: 'utility',
    inputPrice: 0,
    outputPrice: 0.015,
    displayName: 'Image Watermark Remover',
    modelType: 'image',
  },
  {
    model: 'image-zoom',
    vendor: 'utility',
    inputPrice: 0,
    outputPrice: 0.01,
    displayName: 'Image Zoom',
    modelType: 'image',
  },
  // ============================================================================
  // Tripo 3D Models
  // ============================================================================
  {
    model: 'tripo3d-v2.5',
    vendor: 'tripo',
    inputPrice: 0,
    outputPrice: 0.1,
    displayName: 'Tripo 3D V2.5',
    modelType: '3d',
    creativityScore: 85,
  },
  // ============================================================================
  // Moonshot Models
  // ============================================================================
  {
    model: 'moonshot-v1-8k',
    vendor: 'moonshot',
    inputPrice: 0.84,
    outputPrice: 0.84,
    displayName: 'Moonshot V1 8K',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 88,
    contextLength: 8,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'moonshot-v1-32k',
    vendor: 'moonshot',
    inputPrice: 1.68,
    outputPrice: 1.68,
    displayName: 'Moonshot V1 32K',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 85,
    contextLength: 32,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'moonshot-v1-128k',
    vendor: 'moonshot',
    inputPrice: 8.4,
    outputPrice: 8.4,
    displayName: 'Moonshot V1 128K',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 78,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'moonshot-v1-auto',
    vendor: 'moonshot',
    inputPrice: 1.68,
    outputPrice: 1.68,
    displayName: 'Moonshot V1 Auto',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 85,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // ============================================================================
  // Zhipu GLM Models
  // ============================================================================
  {
    model: 'glm-5',
    vendor: 'zhipu',
    inputPrice: 1.5,
    outputPrice: 1.5,
    displayName: 'GLM 5',
    reasoningScore: 95,
    codingScore: 95,
    creativityScore: 92,
    speedScore: 82,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsExtendedThinking: true,
    supportsCacheControl: true,
    recommendedScenarios: ['deep-reasoning', 'coding', 'creative'],
  },
  {
    model: 'glm-4.5',
    vendor: 'zhipu',
    inputPrice: 0.7,
    outputPrice: 0.7,
    displayName: 'GLM 4.5',
    reasoningScore: 88,
    codingScore: 90,
    creativityScore: 85,
    speedScore: 85,
    contextLength: 128,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'glm-4.5-air',
    vendor: 'zhipu',
    inputPrice: 0.14,
    outputPrice: 0.14,
    displayName: 'GLM 4.5 Air',
    reasoningScore: 82,
    codingScore: 85,
    speedScore: 92,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  {
    model: 'glm-4.5-flash',
    vendor: 'zhipu',
    inputPrice: 0.07,
    outputPrice: 0.07,
    displayName: 'GLM 4.5 Flash',
    reasoningScore: 78,
    codingScore: 82,
    speedScore: 96,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  {
    model: 'glm-4-flash',
    vendor: 'zhipu',
    inputPrice: 0.04,
    outputPrice: 0.04,
    displayName: 'GLM 4 Flash',
    reasoningScore: 75,
    codingScore: 78,
    speedScore: 98,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    recommendedScenarios: ['fast-response', 'cost-optimized'],
  },
  // ============================================================================
  // Kimi Models
  // ============================================================================
  {
    model: 'kimi-k2',
    vendor: 'moonshot',
    inputPrice: 2.1,
    outputPrice: 8.4,
    displayName: 'Kimi K2',
    reasoningScore: 92,
    codingScore: 94,
    creativityScore: 88,
    speedScore: 80,
    contextLength: 128,
    supportsFunctionCalling: true,
    supportsStreaming: true,
  },
  // ============================================================================
  // Alibaba Wan Video Models (Additional)
  // ============================================================================
  {
    model: 'wan2.1-14b',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.1,
    displayName: 'Wan 2.1 14B',
    modelType: 'video',
    creativityScore: 88,
  },
  {
    model: 'wan2.1-14b-start-scene-i2v',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.12,
    displayName: 'Wan 2.1 14B Start Scene I2V',
    modelType: 'video',
  },
  {
    model: 'wan2.1-14b-start-end-scene-i2v',
    vendor: 'alibaba',
    inputPrice: 0,
    outputPrice: 0.15,
    displayName: 'Wan 2.1 14B Start End Scene I2V',
    modelType: 'video',
  },
];
